version: '3.9'

services:
  opencode:
    container_name: tray_opencode
    build:
      context: .
    volumes:
      - "./dist/theme:/usr/app"
    command: bash -c "
      opencode configure ${API_KEY} ${PASSWORD} ${THEME_ID} &&
      opencode download &&
      opencode clean &&
      opencode watch"
